#!/usr/bin/env python


import os
import fire
import jinja2


class Miao:
    """
    Project manager for coorperating with
    `CMake`.
    """

    basic_template = """
cmake_minimum_required(VERSION 3.0)
project({{ self.project_name }})
    """

    def new(self, project_name: str):
        """
        Create a new project.
        """
        # Check if directory exists
        current_directory = os.getcwd()
        for file_name in os.listdir():
            if project_name == file_name:
                raise RuntimeError("Already exists")
        os.mkdir(project_name)        
        self.project_name = project_name
        print(f"{self.project_name} created")


if __name__ == "__main__":
    fire.Fire(Miao)
